### PR TITLE
Read payload explicitly as File when mode is ref and content-type json (see also https://github.com/spring-cloud/spring-cloud-stream/issues/1606)

### PR DESCRIPTION
**Pull request by marcpa00**
In test with file.consumer.mode=ref and a json content-type (implicitely the default or explicitly from property), we read back the payload as File.class.

Regardless of how issue https://github.com/spring-cloud/spring-cloud-stream/issues/1606 is solved, maybe it is a good idea to be explicit in the tests : this commit read the received payload as File unless it specified explicitly a text/plain content type.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@marcpa00 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-stream-app-starters/file&pullRequestId=13)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-stream-app-starters/file&pullRequestId=13) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@marcpa00 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-stream-app-starters/file&pullRequestId=13)!

**Comment by artembilan** [comment]
@marcpa00 , 

Please, consider in the future follow commit message recommendations. First of all the headline must be <=50 symbols.

Thank you for contribution anyway; looking forward for more!

**Comment by marcpa00** [comment]
Will do.

**Pull request merged**
